# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapsProjcet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MapsProjcet
  pod 'MBProgressHUD', '~> 0.9'
  pod 'LLARingSpinnerView', '~> 0.1'
end
