
# platform :ios, '9.0'

target 'thirdPartyFrameWork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'DRPLoadingSpinner', '~> 1.3'

end
